apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
    version: "1.0"  # Toggle this value for harmless changes
  annotations:
    last-updated: "2024-11-14"  # Update this date to trigger changes
spec:
  replicas: 3  # Change between different values for testing
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: myregistry/spring-boot-app:latest  # Ensure this is correct
        ports:
        - containerPort: 8080
        resources:  # Optional: Add or modify resource limits and requests
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
